### ISSUE TITLE
Extract Job Postings from Stackoverflow Careers

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/VirtualAgent#3]
http://careers.stackoverflow.com/

---

- [x] Create a query with arguments
- [x] Request RSS feed / XML data for query arguments
- [x] Parse XML
- [x] Transform the Job Postings into our standardized format

**Comment by Glavin001** [comment]
Parse RSS feed: https://github.com/kurtmckee/feedparser

**Comment by Glavin001** [comment]
Advanced query options: http://stackoverflow.com/help/search-jobs

**Comment by Glavin001** [comment]
Example query: http://stackoverflow.com/jobs/feed?searchTerm=Node.js+salary%3a70000&allowsremote=True

**Comment by ChaosSmith** [comment]
Fixed up JSON outputs, works like a charm now. Confirmed indexing into ES
